### ISSUE TITLE
Version 2.0 Release

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-react#276]
This ticket is to track everything we're batching up in #275 for the 2.0 release:

- [x] Remove internal usage of mobx-react `Provider` #259 
- [x] Break `injectTreeNode` into composable parts (and kill autoAdd for now) #272
- [x] Kill Quick Start Story (for now - we'll bring it back later after 2.0 so we can think through it holistically instead of just patching it) #272
- [x] Context Based Theme API (main breaking change is wrapping all the component props into a single prop) #98
- [x] Kill mobx-react-utils #21
- [x] ~Clean up TermsStatsTable API #104~
- [ ] Optional Modal/Popover Lens API #317

**Comment by daedalus28** [comment]
Also up for discussion is whether or not we're going to consider breaking out layout components and/or the grey vest "pure" components that aren't search related. That would likely be a breaking change and so now might be a good idea to do it.

The idea is that we'd probably just have a `grey-vest` component library where all the layout and basic things from grey vest would live, styleable with something like emotion as a pure component library. Contexture-react would then take a dependency on it. Alternatively, we could have them all in a top level folder similar to today's layout components

**Comment by stellarhoof** [comment]
Here's my wishlist:
- Stop exporting CSS classes. Instead rely on exported styled components
- Break up example types into its own repo and make it themeable both through components and styles.

**Comment by michsa** [comment]
We should do a cleanup pass on the `utils` folder in general, actually; there's a bunch of stuff in there that we don't need anymore. Off the top of my head, a couple of the functions in `futil` and all of `dsl` can be killed, and there's probably some more stuff in `search`/`schema` too
